export const SORT_BY="SORT_BY";
export const CATEGORY_NAME="CATEGORY_NAME";
export const SEARCH_TERM="SEARCH_TERM";


export const UPDATE_PLAYLISTS="UPDATE_PLAYLISTS"

export const UPDATE_SINGLE_PLAYLISTS="UPDATE_SINGLE_PLAYLISTS"